In [1]:
#Single Inheritance
class Fruit():
    def __init__(self):
        print("In parents class")
        
class Apple(Fruit):
    def __init__(self):
        super().__init__()  #super for calling parent method
        print("In apple child class ")
    
obj = Apple()

In parents class
In apple child class 


In [2]:
#Multiple Inheritance
class A:
    pass
class B:
    pass
class C(A,B):
    pass
issubclass(C,A) and issubclass(C,B)

True

In [3]:
#Multilevel Inheritance
class A:
    x=1
class B(A):
    pass
class C(B):
    pass

obj = C()
obj.x

1

In [5]:
#Hierarchical Inheritance
class A:
    x=1
class B(A):
    pass
class C(A):
    pass

obj = C()
obj.x
issubclass(B,A) and issubclass(C,A)

True

In [6]:
#Hybrid inheritance
class A:
    x=1
#Hierarchical Inheritance
class B(A):
    pass
class C(A):
    pass
class D(A):
    pass
#Multiple Inheritance
class E(B,D):
    pass

obj = E()
obj.x

1

In [8]:
#Overlaoding Issue
def add(a,b):
    return a+b
def add(a,b,c):
    return a+b+c

#add(2,3)  while ruinng memmory is updated so that why getting error
add(2,3,5)

10

In [10]:
#Oveloading 
def add(instanceof,*args):
    if(instanceof == 'int'):
        result = 0
    if(instanceof == ''):
        result = ''
    if(instanceof == 'float'):
        result = 0.0
    for x in args:
        result+=x
    return result

add('int',1,2,3)
add('float',.0,32.2,1.0)

33.2

In [11]:
#Overriding 
class A:
    def checkit(self):
        print("I am in class A")
        
class B(A):
    def checkit(self):
        print("I am in class B")
        
ob1 = A()
ob2 = B()
ob1.checkit()
ob2.checkit()

I am in class A
I am in class B


In [1]:
#polymorphism
class Shark:
    def swim(self):
        print("Shark can swim")
        
class Clownfish:
    def swim(self):
        print("Clownshif can swim")
        
S = Shark()
C = Clownfish()
for fishes in (S,C):
    print(fishes.swim)
    


<bound method Shark.swim of <__main__.Shark object at 0x7fb08d0d06a0>>
<bound method Clownfish.swim of <__main__.Clownfish object at 0x7fb08d0d0630>>


In [2]:
def ocean(fish):
    fish.swim
    


In [3]:
S = Shark()
C = Clownfish()
ocean(S)
ocean(C)

# Numpy

In [2]:
#Numpy
import numpy as np

In [5]:
list1 = [0,1,23]


In [6]:
list1


[0, 1, 23]

In [7]:
arr = np.array(list1)

In [8]:
arr

array([ 0,  1, 23])

In [9]:
list1 +2


TypeError: can only concatenate list (not "int") to list

In [10]:
arr +2

array([ 2,  3, 25])

In [11]:
arr


array([ 0,  1, 23])

In [12]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]

In [13]:
arr2 = np.array(list2)

In [14]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [15]:
type(arr2)

numpy.ndarray

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2 = np.array(list2 , dtype = 'float')

In [18]:
arr2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [19]:
arr2.astype('int')

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [20]:
xx = arr2.tolist()

In [21]:
xx


[[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]]

In [24]:
arr2.tostring()  #ascii string

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

In [25]:
arr2.tobytes()

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x08@'

# dtype and shap

In [26]:
list2


[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [27]:
arr2.shape

(3, 3)

In [28]:
arr2.dtype


dtype('float64')

In [29]:
arr2.size

9

In [30]:
arr2.ndim

2

In [31]:
arr.ndim

1

In [32]:
arr


array([ 0,  1, 23])

In [33]:
arr * arr

array([  0,   1, 529])

In [34]:
arr


array([ 0,  1, 23])

In [35]:
arr[0]

0

In [36]:
arr[2]

23

In [37]:
arr[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [38]:
arr2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [39]:
arr2 * arr2

array([[1., 1., 1.],
       [4., 4., 4.],
       [9., 9., 9.]])

In [40]:
arr2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [41]:
arr2[0]

array([1., 1., 1.])

In [43]:
arr2[1][0]

2.0

In [45]:
boolarr = arr2<3
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [46]:
arr2[boolarr]

array([1., 1., 1., 2., 2., 2.])

In [47]:
arr2

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [48]:
arr2[::-1]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [49]:
arr2[::-1,]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [50]:
arr2[::-1,::-1]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [51]:
axxx = [[1,2,3],[4,5,6],[7,8,9]]

In [52]:
axxx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [53]:
ax = np.array(axxx)

In [54]:
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
ax = ax[::-1,::-1]

In [59]:
ax

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [60]:
ax[::-1,::-1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
ax[::-1][::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# np.nan , np.inf   (not a number , infinit)

In [62]:
np.nan # number cannot be represent in int,float

nan

In [63]:
np.inf # number which is infinite

inf

In [64]:
arr2[0][0] = np.nan
arr2[1][0] = np.inf

In [65]:
arr2

array([[nan,  1.,  1.],
       [inf,  2.,  2.],
       [ 3.,  3.,  3.]])

In [67]:
np.isnan(arr2)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [68]:
np.isinf(arr2)

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [69]:
missing_flag = np.isinf(arr2) | np.isnan(arr2)

In [70]:
missing_flag

array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

In [71]:
arr2[missing_flag]

array([nan, inf])

In [72]:
arr2

array([[nan,  1.,  1.],
       [inf,  2.,  2.],
       [ 3.,  3.,  3.]])

In [73]:
arr2[missing_flag] = 0

In [74]:
arr2

array([[0., 1., 1.],
       [0., 2., 2.],
       [3., 3., 3.]])

# Statistical operations

In [75]:
#Mean , Std , Var
arr2.mean()

1.6666666666666667

In [76]:
arr2.max()

3.0

In [77]:
arr.min()

0

In [78]:
arr2.std()

1.1547005383792515

In [79]:
arr2.var()

1.3333333333333333

In [81]:
arr2.squeeze()

array([[0., 1., 1.],
       [0., 2., 2.],
       [3., 3., 3.]])

In [82]:
arr2.sort()

In [83]:
arr2

array([[0., 1., 1.],
       [0., 2., 2.],
       [3., 3., 3.]])

In [84]:
arr2.cumsum() #0 , 0+1, 0+1+1 ,...

array([ 0.,  1.,  2.,  2.,  4.,  6.,  9., 12., 15.])

In [89]:
 arr = arr2[:2,:2]  # arr2[row,col]  --- row 0 to 2 --- [0:2]

In [90]:
arr

array([[0., 1.],
       [0., 2.]])

In [91]:
arr2[1:3,1:3]

array([[2., 2.],
       [3., 3.]])

In [92]:
arr2[1:3,1:2]

array([[2.],
       [3.]])

In [93]:
arr2.reshape(2,3)

ValueError: cannot reshape array of size 9 into shape (2,3)

In [94]:
arr2.reshape(1,9)   # Here it is 2 Dimension

array([[0., 1., 1., 0., 2., 2., 3., 3., 3.]])

In [95]:
arr2.reshape(9,1)

array([[0.],
       [1.],
       [1.],
       [0.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [102]:
a = arr2.flatten() #convert it in single dimension Arraay
a #copy

array([0., 1., 1., 0., 2., 2., 3., 3., 3.])

In [103]:
b = arr2.ravel() # anychange in new array affect the parent array and it is more efficient
b #Reference that means if any value chnage in b then actucal value in arr2 also chnages

array([0., 1., 1., 0., 2., 2., 3., 3., 3.])

In [104]:
arr2

array([[0., 1., 1.],
       [0., 2., 2.],
       [3., 3., 3.]])

In [106]:
b[0] = -1

In [107]:
arr2

array([[-1.,  1.,  1.],
       [ 0.,  2.,  2.],
       [ 3.,  3.,  3.]])

# Sequence , repitations and random numbers

In [108]:
np.arange(1,5, dtype='int')

array([1, 2, 3, 4])

In [109]:
np.arange(1,50,2) # even no

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [110]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [111]:
np.linspace(1,50,10)   # (start,end,no of equal no can say) -- c numbers only (1,50,2) -- no. is leanear

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [112]:
np.linspace(1,50,100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [113]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [114]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [115]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [116]:
a=[1,2,3]

In [118]:
np.tile(a,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [119]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [120]:
np.repeat(arr2,3)

array([-1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  2.,
        2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.])

In [121]:
np.tile(arr2,3)

array([[-1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.],
       [ 0.,  2.,  2.,  0.,  2.,  2.,  0.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]])

In [123]:
np.random.rand(3,3) #Unifromly distributed 0 to 1

array([[0.0571629 , 0.73199129, 0.65246615],
       [0.00275568, 0.85639171, 0.78546285],
       [0.7299723 , 0.32531508, 0.61581886]])

In [124]:
np.random.randn(3,3) #Normally distributed -1 to 1

array([[ 0.92259995,  1.36992399,  0.9491044 ],
       [-0.29335389,  0.98105998, -1.17893013],
       [ 0.67583151,  0.23277377, -2.2193211 ]])

In [127]:
np.random.randint(0,10,[3,3])

array([[9, 6, 8],
       [2, 5, 2],
       [0, 8, 7]])

In [139]:
np.random.seed(None)  # random changes value everytime
np.random.randint(0,10,[3,3])

array([[4, 7, 9],
       [9, 3, 5],
       [5, 8, 0]])

In [141]:
np.random.seed(0)  # random fixed value everytime
np.random.randint(0,10,[3,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [143]:
np.unique(arr2)

array([-1.,  0.,  1.,  2.,  3.])

In [144]:
unique , count = np.unique(arr2 , return_counts=True)

In [145]:
unique  #Unique Numbers in array

array([-1.,  0.,  1.,  2.,  3.])

In [146]:
count #how many time unique no is repeted

array([1, 1, 2, 2, 3])

In [3]:
np

<module 'numpy' from '/home/ansari/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>

In [4]:
newarr = np.array([9,5,1,2,3,6,8,4,7])

In [5]:
index_gt10 = np.where(newarr>5)  #Where value greater than 5, return index  

In [6]:
index_gt10

(array([0, 5, 6, 8]),)

In [7]:
newarr[index_gt10]

array([9, 6, 8, 7])

In [8]:
newarr[newarr>5]

array([9, 6, 8, 7])

In [9]:
newarr>5

array([ True, False, False, False, False,  True,  True, False,  True])

In [11]:
np.where(newarr > 5 , 'T' , 'F')  # where(condition,If true , If false)

array(['T', 'F', 'F', 'F', 'F', 'T', 'T', 'F', 'T'], dtype='<U1')

In [12]:
newarr.max()

9

In [13]:
newarr.argmax()

0

In [14]:
newarr.argmin()

2

In [15]:
newarr[newarr.argmax()]

9

In [16]:
newarr[newarr.argmin()]

1

# Read and write csv file

In [ ]:
#np.genfromtxt() It load all types of data , It read all data in Int
#np.loadtxt() only one form of type of data

In [19]:
np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1)

array([[ 18.,   8., 307., ...,  70.,   1.,  nan],
       [ 15.,   8., 350., ...,  70.,   1.,  nan],
       [ 18.,   8., 318., ...,  70.,   1.,  nan],
       ...,
       [ 32.,   4., 135., ...,  82.,   1.,  nan],
       [ 28.,   4., 120., ...,  82.,   1.,  nan],
       [ 31.,   4., 119., ...,  82.,   1.,  nan]])

In [21]:
data = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1,
              filling_values=-1000 , dtype='float')

In [24]:
data.ndim

2

In [25]:
data.shape

(392, 9)

In [29]:
np.set_printoptions(suppress=True) #Spressing scintific notations
data[0:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [30]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1,
              dtype = None)

/home/ansari/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [31]:
data2[0:3]

array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [34]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',',skip_header=1,
              dtype = 'object')
data2[:3]

array([[b'18', b'8', b'307', b'130', b'3504', b'12', b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', b'165', b'3693', b'11.5', b'70', b'1',
        b'"buick skylark 320"'],
       [b'18', b'8', b'318', b'150', b'3436', b'11', b'70', b'1',
        b'"plymouth satellite"']], dtype=object)

In [35]:
np.savetxt('data.csv', data, delimiter='')

In [36]:
np.save('data.npy',data)

In [37]:
np.savez('data.npz',data2)

In [38]:
d = np.load('data.npy')

In [39]:
d2 = np.load('data.npz')

In [40]:
d2

In [41]:
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [45]:
d2.files

['arr_0']

In [44]:
d2['arr_0']

array([[b'18', b'8', b'307', ..., b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', ..., b'70', b'1', b'"buick skylark 320"'],
       [b'18', b'8', b'318', ..., b'70', b'1', b'"plymouth satellite"'],
       ...,
       [b'32', b'4', b'135', ..., b'82', b'1', b'"dodge rampage"'],
       [b'28', b'4', b'120', ..., b'82', b'1', b'"ford ranger"'],
       [b'31', b'4', b'119', ..., b'82', b'1', b'"chevy s-10"']],
      dtype=object)