# Concat with row and col wise

In [2]:
import numpy as np

In [6]:
arr1 = np.zeros([4,4])
arr2 = np.ones([4,4])

In [7]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.concatenate, np.vstack by vertically , np.hstack by horizontally , np.r_ by row wise , np.c_ by colmn

In [12]:
np.concatenate([arr1,arr2],axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.vstack([arr1,arr2])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.r_[arr1,arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.hstack([arr1,arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [17]:
np.c_[arr1,arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

# Sort a numpy array

In [14]:
arr = np.random.randint(1,10,size=[10,5])

In [19]:
arr

array([[4, 4, 6, 5, 2],
       [1, 2, 8, 9, 9],
       [7, 3, 4, 9, 8],
       [1, 7, 1, 2, 4],
       [2, 5, 6, 8, 8],
       [3, 6, 3, 4, 2],
       [7, 6, 7, 2, 9],
       [7, 6, 2, 1, 5],
       [9, 1, 1, 8, 3],
       [5, 6, 9, 1, 9]])

In [20]:
np.sort(arr)

array([[2, 4, 4, 5, 6],
       [1, 2, 8, 9, 9],
       [3, 4, 7, 8, 9],
       [1, 1, 2, 4, 7],
       [2, 5, 6, 8, 8],
       [2, 3, 3, 4, 6],
       [2, 6, 7, 7, 9],
       [1, 2, 5, 6, 7],
       [1, 1, 3, 8, 9],
       [1, 5, 6, 9, 9]])

In [24]:
np.sort(arr, axis = 0)

array([[1, 1, 1, 1, 2],
       [1, 2, 1, 1, 2],
       [2, 3, 2, 2, 3],
       [3, 4, 3, 2, 4],
       [4, 5, 4, 4, 5],
       [5, 6, 6, 5, 8],
       [7, 6, 6, 8, 8],
       [7, 6, 7, 8, 9],
       [7, 6, 8, 9, 9],
       [9, 7, 9, 9, 9]])

In [26]:
arr_index = arr[:,0].argsort()

In [27]:
arr[arr_index]

array([[1, 2, 8, 9, 9],
       [1, 7, 1, 2, 4],
       [2, 5, 6, 8, 8],
       [3, 6, 3, 4, 2],
       [4, 4, 6, 5, 2],
       [5, 6, 9, 1, 9],
       [7, 3, 4, 9, 8],
       [7, 6, 7, 2, 9],
       [7, 6, 2, 1, 5],
       [9, 1, 1, 8, 3]])

In [28]:
arr

array([[4, 4, 6, 5, 2],
       [1, 2, 8, 9, 9],
       [7, 3, 4, 9, 8],
       [1, 7, 1, 2, 4],
       [2, 5, 6, 8, 8],
       [3, 6, 3, 4, 2],
       [7, 6, 7, 2, 9],
       [7, 6, 2, 1, 5],
       [9, 1, 1, 8, 3],
       [5, 6, 9, 1, 9]])

# working with dates

In [31]:
d = np.datetime64('2020-01-02 21:23:00')

In [32]:
d

numpy.datetime64('2020-01-02T21:23:00')

In [33]:
d + 2 #seconds

numpy.datetime64('2020-01-02T21:23:02')

In [34]:
oneday = np.timedelta64(1,'D')

In [35]:
oneday

numpy.timedelta64(1,'D')

In [36]:
d + oneday

numpy.datetime64('2020-01-03T21:23:00')

In [38]:
onemin = np.timedelta64(1,'m')

In [39]:
d + onemin

numpy.datetime64('2020-01-02T21:24:00')

In [9]:
da = np.arange(np.datetime64('2020-01-01'),np.datetime64('2020-02-01'),4)

In [10]:
da

array(['2020-01-01', '2020-01-05', '2020-01-09', '2020-01-13',
       '2020-01-17', '2020-01-21', '2020-01-25', '2020-01-29'],
      dtype='datetime64[D]')

# numpy advance function

In [ ]:
#vectorize

In [11]:
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2
    
foo(10)

5.0

In [21]:
foo_vec = np.vectorize(foo,otypes=[float])

In [18]:
arr

array([[1, 2, 7, 8, 2],
       [7, 7, 9, 6, 8],
       [7, 2, 1, 9, 7],
       [1, 4, 3, 3, 7],
       [1, 6, 8, 2, 1],
       [8, 2, 7, 2, 8],
       [7, 4, 5, 6, 4],
       [3, 6, 9, 9, 5],
       [8, 3, 6, 8, 8],
       [3, 7, 9, 2, 1]])

In [19]:
foo_vec[arr]

TypeError: only integer scalar arrays can be converted to a scalar index