# Pytorch
- PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab (FAIR). It is free and open-source software released under the Modified BSD license. Although the Python interface is more polished and the primary focus of development, PyTorch also has a C++ interface.
- A number of pieces of Deep Learning software are built on top of PyTorch, including Uber's Pyro, HuggingFace's Transformers, and Catalyst.
- It is also one of the preferred deep learning research platforms built to provide maximum flexibility and speed. It is known for providing two of the most high-level features; namely, tensor computations with strong GPU acceleration support and building deep neural networks on a tape-based autograd systems.

# Pytorch : Tensors
- A PyTorch Tensor is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic n-dimensional array to be used for arbitrary numeric computation.
- The biggest difference between a numpy array and a PyTorch Tensor is that a PyTorch Tensor can run on either CPU or GPU.

# Math operations

### Most common opeartions

Here are some functions
- torch.abs()
- torch.add()
- torch.div()
- torch.mul()
- torch.neg()
- torch.pow()
- torch.reciprocal()
- torch.remainder()
- torch.square()
- torch.sqrt()

In [3]:
# First install torch library by following commands if not installed in your system
# !conda install pytorch cpuonly -c pytorch -y

In [4]:
# Importing pytorch library
import torch

## 1. torch.abs()

### torch.abs(input, out=None) → Tensor
Computes the element-wise absolute value of the given input tensor.

out = | input |

### Parameters
- input (Tensor) – the input tensor.

- out (Tensor, optional) – the output tensor.

Example 1:

In [46]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

Example 2:

In [47]:
torch.abs(torch.tensor([-1, -2, 3.2]))

tensor([1.0000, 2.0000, 3.2000])

Example 3:

In [48]:
torch.abs(torch.tensor([-1, -2, 3, 'a']))

TypeError: new(): invalid data type 'str'

## 2. torch.add()

### torch.add(input, other, out=None)
Adds the scalar other to each element of the input input and returns a new resulting tensor.

out = input + other

### Parameters
- input (Tensor) – the input tensor.

- value (Number) – the number to be added to each element of input

Example 1:

In [10]:
a = torch.randn(4)
a

tensor([ 1.3668, -0.7994,  0.0833,  1.0099])

In [11]:
torch.add(a, 20)

tensor([21.3668, 19.2006, 20.0833, 21.0099])

Example 2:

In [13]:
torch.add(a, -0.22)

tensor([ 1.1468, -1.0194, -0.1367,  0.7899])

Example 3:

In [49]:
torch.add(a, '20')

TypeError: add(): argument 'other' (position 2) must be Tensor, not str

## 3. torch.sub()

### torch.sub(input,other, out=None) → Tensor
Subtract the scalar other to each element of the input input and returns a new resulting tensor.

out = input - other

### Parameters
- input (Tensor) – the input tensor.

- other (Number) – the number to be subtracted to each element of input

Example 1:

In [72]:
a = torch.randn(4)
a

tensor([ 0.9340,  0.6707, -0.5573,  2.0313])

In [73]:
torch.sub(a,2)

tensor([-1.0660, -1.3293, -2.5573,  0.0313])

Example 2:

In [74]:
torch.sub(a,-2)

tensor([2.9340, 2.6707, 1.4427, 4.0313])

Example 3:

In [76]:
torch.sub(a,'2')

TypeError: sub(): argument 'other' (position 2) must be Tensor, not str

## 4. torch.div()

### torch.div(input, other, out=None) → Tensor
Divides each element of the input input with the scalar other and returns a new resulting tensor.

out = input / other

### Parameters
- input (Tensor) – the input tensor.

- other (Number) – the number to be divided to each element of input


Example 1:

In [15]:
a = torch.randn(5)
a

tensor([-1.0400,  0.6889,  1.0433, -0.4652,  0.5377])

In [17]:
torch.div(a, 0.2)

tensor([-5.1998,  3.4445,  5.2167, -2.3261,  2.6886])

Example 2:

In [18]:
a = torch.randn(4, 4)
a

tensor([[-0.4013,  1.9533, -0.6859, -0.0113],
        [-0.1162, -0.7545, -0.9180, -0.2901],
        [ 0.7088, -0.3915,  2.6670,  0.7693],
        [-1.4068, -1.1885,  0.0826, -0.5794]])

In [19]:
b = torch.randn(4)
b

tensor([ 0.3743,  1.6942,  0.7239, -0.2715])

In [20]:
torch.div(a, b)

tensor([[-1.0719,  1.1529, -0.9474,  0.0418],
        [-0.3105, -0.4453, -1.2680,  1.0686],
        [ 1.8935, -0.2311,  3.6839, -2.8337],
        [-3.7582, -0.7015,  0.1142,  2.1342]])

Example 3:

In [51]:
a = torch.randn(5)
a
torch.div(a, 0)

tensor([inf, inf, -inf, -inf, inf])

## 5. torch.mul()

### torch.mul(input, other, out=None)
Multiplies each element of the input input with the scalar other and returns a new resulting tensor.

out = input * other

### Parameters
- input (Tensor) – the input tensor.

- other (Number) – the number to be multiplied to each element of input


Example 1:

In [52]:
a = torch.randn(3)
a

tensor([ 1.4657, -0.4368, -1.3719])

In [53]:
torch.mul(a, 100)

tensor([ 146.5715,  -43.6829, -137.1900])

Example 2:

In [54]:
a = torch.randn(4, 1)
a

tensor([[ 0.8809],
        [-0.3604],
        [ 1.9949],
        [-0.7383]])

In [55]:
b = torch.randn(1, 4)
b

tensor([[ 0.1985, -1.3562, -2.7299,  0.4045]])

In [56]:
torch.mul(a, b)

tensor([[ 0.1749, -1.1947, -2.4049,  0.3563],
        [-0.0716,  0.4888,  0.9840, -0.1458],
        [ 0.3960, -2.7054, -5.4459,  0.8068],
        [-0.1466,  1.0013,  2.0155, -0.2986]])

Example 3:

In [57]:
a = torch.randn(3)
a
torch.mul(a, 0)

tensor([-0., 0., 0.])

## 6. torch.neg()

### torch.neg(input, out=None) → Tensor
Returns a new tensor with the negative of the elements of input.

out = −1 × input

### Parameters
- input (Tensor) – the input tensor.

- out (Tensor, optional) – the output tensor.

Example :

In [29]:
a = torch.randn(5) 
a

tensor([ 0.9945,  0.8465,  0.8460,  0.9295, -1.0264])

In [30]:
torch.neg(a)

tensor([-0.9945, -0.8465, -0.8460, -0.9295,  1.0264])

## 7. torch.pow()

### torch.pow(input, exponent, out=None) → Tensor
Takes the power of each element in input with exponent and returns a tensor with the result.

exponent can be either a single float number or a Tensor with the same number of elements as input.

out = input^exponent

### Parameters
- input (Tensor) – the input tensor.

- exponent (float or tensor) – the exponent value

- out (Tensor, optional) – the output tensor.

Example 1:

In [61]:
a = torch.arange(1., 5.)
a

tensor([1., 2., 3., 4.])

In [37]:
torch.pow(a, 2)

tensor([ 1.,  4.,  9., 16.])

Example 2:

In [63]:
torch.pow(a, 0)

tensor([1., 1., 1., 1.])

## 8. torch.reciprocal()

### torch.reciprocal(input, out=None) → Tensor
Returns a new tensor with the reciprocal of the elements of input.

out = 1 / input

### Parameters
- input (Tensor) – the input tensor.

- out (Tensor, optional) – the output tensor.

Example :

In [38]:
a = torch.randn(4)
a

tensor([-0.3585, -1.4333, -0.1978,  2.1530])

In [39]:
torch.reciprocal(a)

tensor([-2.7892, -0.6977, -5.0563,  0.4645])

## 9. torch.remainder()

### torch.remainder(input, other, out=None) → Tensor
Computes the element-wise remainder of division.

The divisor and dividend may contain both for integer and floating point numbers. The remainder has the same sign as the divisor.

out = input % other

### Parameters
- input (Tensor) – the dividend

- other (Tensor or float) – the divisor that may be either a number or a Tensor of the same shape as the dividend

- out (Tensor, optional) – the output tensor.

Example 1:

In [40]:
torch.remainder(torch.tensor([-3., -2, -1, 1, 2, 3]), 2)

tensor([1., 0., 1., 1., 0., 1.])

Example 2:

In [41]:
torch.remainder(torch.tensor([-3., -2, -1, 1, 2, 3]), -2)

tensor([-1.,  0., -1., -1.,  0., -1.])

## 10. torch.square()

### torch.square(input, out=None) → Tensor
Returns a new tensor with the square of the elements of input.

out = input * input

### Parameters
- input (Tensor) – the input tensor.

- out (Tensor, optional) – the output tensor.

Example :

In [42]:
a = torch.randn(4)
a

tensor([ 0.3085, -0.3320,  0.0469, -1.2137])

In [43]:
torch.square(a)

tensor([0.0952, 0.1102, 0.0022, 1.4730])